In [1]:
import random
import numpy as np
import networkx as nx
import networkit as nk
from typing import Union
from collections import deque
from littleballoffur.sampler import Sampler
import torch
import torch_geometric.transforms as T
from torch_geometric.datasets.dblp import DBLP
import matplotlib.pyplot as plt
from torch_geometric.utils import to_networkx

NKGraph = type(nk.graph.Graph())
NXGraph = nx.classes.graph.Graph

Small graphs are obtained from real datasets by modifying the ForestFireSampler code in https://little-ball-of-fur.readthedocs.io/en/latest/_modules/littleballoffur/exploration_sampling/forestfiresampler.html

In [2]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
import csv
import random
import os

from littleballoffur import ForestFireSampler
import time

In [3]:
class ForestFireSampler(Sampler):
    r"""An implementation of forest fire sampling. The procedure is a stochastic
    snowball sampling method where the expansion is proportional to the burning probability.
    `"For details about the algorithm see this paper." <https://cs.stanford.edu/people/jure/pubs/sampling-kdd06.pdf>`_


    Args:
        number_of_nodes (int): Number of sampled nodes. Default is 100.
        p (float): Burning probability. Default is 0.4.
        seed (int): Random seed. Default is 42.
    """

    def __init__(
            self,
            number_of_nodes: int = 100,
            p: float = 0.4,
            seed: int = 42,
            max_visited_nodes_backlog: int = 100,
            restart_hop_size: int = 10,
    ):
        self.number_of_nodes = number_of_nodes
        self.p = p
        #self.seed = seed
        #self._set_seed()
        self.restart_hop_size = restart_hop_size
        self.max_visited_nodes_backlog = max_visited_nodes_backlog

    def _create_node_sets(self, graph):
        """
        Create a starting set of nodes.
        """
        self._sampled_nodes = set()
        self._set_of_nodes = set(range(self.backend.get_number_of_nodes(graph)))
        self._visited_nodes = deque(maxlen=self.max_visited_nodes_backlog)

    def _start_a_fire(self, graph):
        """
        Starting a forest fire from a single node.
        """
        remaining_nodes = list(self._set_of_nodes.difference(self._sampled_nodes))
        #seed_node = random.choice(remaining_nodes)
        #modified code to select start node from the list of Author nodes
        author_nodes= [x for x, y in undirected_dblp.nodes(data=True) if y['type'] == 'author']
        seed_node = random.choice(author_nodes)
        self._sampled_nodes.add(seed_node)
        node_queue = deque([seed_node])
        while len(self._sampled_nodes) < self.number_of_nodes:
            if len(node_queue) == 0:
                node_queue = deque(
                    [
                        self._visited_nodes.popleft()
                        for k in range(
                        min(self.restart_hop_size, len(self._visited_nodes))
                    )
                    ]
                )
                if len(node_queue) == 0:
                    print(
                        "Warning: could not collect the required number of nodes. The fire could not find enough nodes to burn."
                    )
                    break
            top_node = node_queue.popleft()
            self._sampled_nodes.add(top_node)
            neighbors = set(self.backend.get_neighbors(graph, top_node))
            unvisited_neighbors = neighbors.difference(self._sampled_nodes)
            score = np.random.geometric(self.p)
            count = min(len(unvisited_neighbors), score)
            burned_neighbors = random.sample(unvisited_neighbors, count)
            self._visited_nodes.extendleft(
                unvisited_neighbors.difference(set(burned_neighbors))
            )
            for neighbor in burned_neighbors:
                if len(self._sampled_nodes) >= self.number_of_nodes:
                    break
                node_queue.extend([neighbor])

    def sample(self, graph: Union[NXGraph, NKGraph]) -> Union[NXGraph, NKGraph]:
        """
        Sampling nodes iteratively with a forest fire sampler.

        Arg types:
            * **graph** *(NetworkX or NetworKit graph)* - The graph to be sampled from.

        Return types:
            * **new_graph** *(NetworkX or NetworKit graph)* - The graph of sampled nodes.
        """
        self._deploy_backend(graph)
        self._check_number_of_nodes(graph)
        self._create_node_sets(graph)
        while len(self._sampled_nodes) < self.number_of_nodes:
            self._start_a_fire(graph)
        new_graph = self.backend.get_subgraph(graph, self._sampled_nodes)
        return new_graph

In [4]:
def plot_graph(G,attribute):

    color_class_map = {0: 'blue', 1: 'red', 2: 'darkgreen', 3: 'orange'}

    nx.draw(G, 
        with_labels=True, node_color=[color_class_map[node[1][attribute]] 
                        for node in G.nodes(data=True)], 
            node_size=200,
        font_color='black')
    plt.show()

DBLP

In [5]:
dataset = DBLP(root='./dblp_data', transform=T.Constant(node_types='conference'))
data = dataset[0]

Downloading https://www.dropbox.com/s/yh4grpeks87ugr2/DBLP_processed.zip?dl=1
Extracting dblp_data/raw/DBLP_processed.zip
Processing...
Done!

In [6]:
def get_node_types(G):
    for n in G.nodes:
        if G.nodes[n]['type'] == 'author':
            G.nodes[n]['type'] = 1
        elif G.nodes[n]['type'] == 'paper':
            G.nodes[n]['type'] = 0
        elif G.nodes[n]['type'] == 'term':
            G.nodes[n]['type'] = 2
        elif G.nodes[n]['type'] == 'conference':
            G.nodes[n]['type'] = 3

In [7]:
def feature_selection(df_sampled):
    col_sum = df_sampled.sum(axis=0)
    sorted_colsum = sorted(col_sum, reverse=True)
    index_list = []
    for i in sorted_colsum[:50]:
        index_list.append(list(col_sum).index(i))
    imp_feat = df_sampled[index_list]
    return imp_feat

In [8]:
#Original author node features
author = data['author'].x.tolist()
author_df = pd.DataFrame(author)
author_df['class'] = data['author'].y.tolist()
author_df

,0,1,2,3,4,5,6,7,8,9,...,325,326,327,328,329,330,331,332,333,class
0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2
1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4052,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
4053,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
4054,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
4055,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
4056,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0

In [9]:
author_class0 = author_df[author_df['class'] == 0].drop(['class'], axis = 1)
author_class0 = author_class0.reset_index(drop=True)
author_class0 = feature_selection(author_class0)
author_class0

,63,64,295,222,65,221,23,296,162,88,...,22,22,251,9,137,137,124,13,13,44
0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1192,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1193,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1194,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1195,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1196,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [10]:
author_class1 = author_df[author_df['class'] == 1].drop(['class'], axis = 1)
author_class1= author_class1.reset_index(drop=True)
author_class1 = feature_selection(author_class1)
author_class1

,63,170,321,23,39,152,88,35,15,65,...,77,77,77,302,80,80,185,314,64,64
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
3,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
740,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
741,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
742,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
743,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
744,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [11]:
author_class2 = author_df[author_df['class'] == 2].drop(['class'], axis = 1)
author_class2= author_class2.reset_index(drop=True)
author_class2 = feature_selection(author_class2)
author_class2

,152,23,321,148,228,295,15,15,296,11,...,83,72,188,21,21,21,21,21,173,60
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
3,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1104,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1105,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1106,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1107,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1108,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [12]:
author_class3 = author_df[author_df['class'] == 3].drop(['class'], axis = 1)
author_class3= author_class3.reset_index(drop=True)
author_class3 = feature_selection(author_class3)
author_class3

,242,135,23,321,253,329,302,222,81,295,...,88,206,206,101,106,106,106,151,151,97
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0
3,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1001,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1002,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1003,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1004,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1005,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [13]:
#Original paper node features
paper = data['paper'].x.tolist()
paper_df = pd.DataFrame(paper)
paper_df= paper_df.reset_index(drop=True)
paper_df = feature_selection(paper_df)
paper_df

,11,31,950,955,3074,4065,2081,2358,2338,1866,...,3691,3703,3969,1330,2161,3444,1201,1057,2967,3430
0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14323,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14324,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14325,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14326,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
14327,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [14]:
#Original paper node features
term = data['term'].x.tolist()
term_df = pd.DataFrame(term)
term_df = term_df.reset_index(drop=True)
term_df

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
0,-0.69241,-0.465920,1.154000,0.066483,-0.676250,0.693760,0.53680,0.206780,0.12607,-0.36763,...,1.32870,0.074684,-0.34136,0.873600,-0.065725,-0.780720,0.902000,0.917840,0.19945,-0.63601
1,1.20310,-0.400280,0.073991,1.041500,0.051753,0.411660,-0.98656,-0.794660,0.36033,0.54428,...,0.38339,-0.572190,-0.16915,0.139840,-0.774300,-0.061819,0.218870,1.326200,-0.33245,0.81980
2,0.37481,0.573140,0.480170,-0.056679,0.704740,0.715910,0.32591,-0.099446,0.51029,0.64193,...,0.74200,-0.163610,0.44295,0.400600,-0.235400,-0.276530,-0.203020,1.152200,0.60099,-0.43094
3,0.54148,-0.419840,-0.334260,-0.412010,0.112200,1.047600,0.47449,-0.751110,0.40817,0.74477,...,0.45971,-0.064420,-0.27582,1.021800,-0.037676,-0.405910,1.231400,0.472220,0.69127,0.37195
4,0.16408,0.927990,-1.573400,-0.859870,0.369720,0.852800,0.20269,-0.620400,-1.00010,0.29585,...,0.66077,-0.952820,-0.36583,1.758900,-0.497820,0.599950,0.756170,1.384800,-0.11633,-0.62254
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7718,0.41800,0.249680,-0.412420,0.121700,0.345270,-0.044457,-0.49688,-0.178620,-0.00066,-0.65660,...,-0.29871,-0.157490,-0.34758,-0.045637,-0.442510,0.187850,0.002785,-0.184110,-0.11514,-0.78581
7719,-1.01450,1.239400,-1.618500,-1.033600,-0.056811,0.270890,-0.38817,-0.353350,-0.51784,1.10460,...,0.97806,0.158320,-0.54189,-0.186700,-0.334690,0.391300,0.524110,-0.059546,-0.78882,-0.71343
7720,0.41800,0.249680,-0.412420,0.121700,0.345270,-0.044457,-0.49688,-0.178620,-0.00066,-0.65660,...,-0.29871,-0.157490,-0.34758,-0.045637,-0.442510,0.187850,0.002785,-0.184110,-0.11514,-0.78581
7721,0.17239,-0.272270,-1.336800,1.170600,-0.621270,-0.528470,1.32210,0.145990,-0.15398,-1.24660,...,-0.76113,-0.583970,-0.13828,0.907620,-0.114690,-0.746190,0.723290,-0.088101,0.02252,0.11660
7722,0.21966,0.025267,0.122040,0.026020,-0.389860,1.348100,0.60502,0.633490,0.69220,-0.57375,...,-0.56460,-0.571180,-0.74330,0.762680,0.648750,-0.731060,1.562300,0.087148,-0.53515,-0.49489

In [15]:
def remap_indices(G):
    val_list = [*range(0, G.number_of_nodes(), 1)]
    return dict(zip(G,val_list))

In [16]:
def add_node_features(G):
    for n in G.nodes:
        node_type = G.nodes[n]["type"] 
        
        if node_type == 0:
            node_id = n
            paper_node_feature = paper_df.loc[int(node_id), :].values.flatten().tolist()
            G.nodes[n]["feature"] = paper_node_feature 

        elif node_type == 1:
            node_id = n
            node_class = G.nodes[n]["class"]
            
            if node_class == 0:
                author_node_feature = author_class0.loc[int(node_id), :].values.flatten().tolist()
                G.nodes[n]["feature"] = author_node_feature 
                G.nodes[n]["class"] = node_class

            elif node_class == 1:
                author_node_feature = author_class1.loc[int(node_id), :].values.flatten().tolist()
                G.nodes[n]["feature"] = author_node_feature 
                G.nodes[n]["class"] = node_class

            elif node_class == 2:                
                author_node_feature = author_class2.loc[int(node_id), :].values.flatten().tolist()
                G.nodes[n]["feature"] = author_node_feature 
                G.nodes[n]["class"] = node_class
                
            elif node_class == 3:     
                author_node_feature = author_class3.loc[int(node_id), :].values.flatten().tolist()
                G.nodes[n]["feature"] = author_node_feature 
                G.nodes[n]["class"] = node_class
                
        elif node_type == 2:
            node_id = n
            term_node_feature = term_df.loc[int(node_id), :].values.flatten().tolist()
            G.nodes[n]["feature"] = term_node_feature 
        elif node_type == 3:
            node_id = n
            term_node_feature = np.zeros(50)
            G.nodes[n]["feature"] = term_node_feature

    return G

In [17]:
networkX_dblp_graph = to_networkx(data)
undirected_dblp = networkX_dblp_graph.to_undirected()
nodes_attr = author_df[['class']].set_index(author_df.index).to_dict(orient = 'index')
nx.set_node_attributes(undirected_dblp, nodes_attr)
adj_list= []
node_type_list = []
node_feature_list = []
for i in range(0,200):
    model = ForestFireSampler(15)
    graph = model.sample(undirected_dblp)
    if nx.is_connected(graph):
        mapping = remap_indices(graph)
        graph = nx.relabel_nodes(graph, mapping)
        
        get_node_types(graph)
        graph = add_node_features(graph)
        
        A = nx.adjacency_matrix(graph)
        adj = torch.tensor(np.asarray(A.todense()))
        adj_list.append(adj)
        
        node_type = nx.get_node_attributes(graph, "type")
        node_feature = nx.get_node_attributes(graph, "feature")
        
        node_type_list.append(list(node_type.values()))
        node_feature_list.append(list(node_feature.values()))
        
    else:
        print('Disconnected graph')

In [18]:
len(adj_list)

200

In [19]:
#Save graphs with node features and node types for graph generation using VAE(baseline)
torch.save([adj_list,node_type_list,node_feature_list],'real_dblp_vae_15.pt')

In [20]:
#Load graphs
adjs, node_types, node_feats = torch.load('real_dblp_vae_15.pt')

In [21]:
for i, adj in enumerate(adjs[:1]):
    print('adjacency matrix', adj)
    print('node types', node_types[i])
    print('node features', node_feats[i])

adjacency matrix tensor([[0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0],
        [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]])
node types [0, 0, 0, 0, 2, 2, 2, 1, 0, 2, 2, 0, 2, 1, 0]
node features [[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0], [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.16407999396324158, 0.9279900193214417, -1.5734000205993652, -0.8598700165748596, 0.3697200119495392, 0.8528000116348267, 0.2026900053024292, -0.6204000115394592, -1.000100016593933, 0.29585000872612, -0.7832499742507935, 0.5728300213813782, -0.6292799711227417, -0.019884999841451645, -0.8359799981117249, -0.6436100006103516, 0.24201999604701996, -0.33750998973846436, 0.15238000452518463, -0.12740999460220337, 0.21904000639915466, 0.7608299851417542, 0.13383999466896057, -0.031021999195218086, 1.1717000007629395, -0.6394500136375427, -1.0902999639511108, -0.1693899929523468, -0.33952000737190247, 0.6442199945449829, 1.8583999872207642, -0.8699100017547607, 0.16362999379634857, -1.0680999755859375, -0.5793200135231018, -0.5610499978065491, -1.1629999876022339, 0.4985100030899048, -0.07184399664402008, 0.46303999423980713, 0.6607699990272522, -0.9528200030326843, -0.3658300042152405, 1.7589000463485718, -0.4978199899196625, 0.5999500155448914, 0.7561699748039246, 1.3847999572753906, -0.11632999777793884, -0.6225399971008301], [0.7506800293922424, 0.053126998245716095, 0.05462700128555298, 0.072503000497818, -0.12020999938249588, 0.8271700143814087, 0.19641000032424927, -0.3117299973964691, 0.36421999335289, -0.33243000507354736, 0.2528899908065796, 0.3469099998474121, -0.9692100286483765, -0.26155999302864075, 0.9512699842453003, 0.6160500049591064, 0.36542999744415283, 0.19097000360488892, 0.5557100176811218, -0.48399999737739563, -0.7612500190734863, -0.26583999395370483, -0.2206999957561493, 0.33208999037742615, 0.7944599986076355, -1.881700038909912, -0.13826000690460205, 0.34505000710487366, 0.792959988117218, 0.4883800148963928, 3.2985999584198, 0.17404000461101532, -0.0724250003695488, -0.8868100047111511, -0.3127700090408325, 0.3091599941253662, -0.32530999183654785, 0.10030999779701233, 0.6990600228309631, 0.22572000324726105, -0.5838500261306763, 0.3680500090122223, 0.06333599984645844, 0.8871600031852722, 0.25598999857902527, 0.15023000538349152, 0.5453900098800659, 0.9743599891662598, 0.2740100026130676, 0.10774999856948853], [0.4299199879169464, 0.6545400023460388, -1.8559000492095947, 0.19212999939918518, 0.45833998918533325, 0.246069997549057, 0.23594999313354492, 0.20942999422550201, -0.6368399858474731, -0.20799000561237335, -0.08039099723100662, -0.17476999759674072, 0.2612000107765198, -0.12915000319480896, 0.22975000739097595, 0.18571999669075012, -0.9606599807739258, -0.7127900123596191, 0.7088800072669983, -0.6547799706459045, 0.9127900004386902, 0.32440999150276184, -0.547950029373169, -0.4630799889564514, -0.42072001099586487, -1.0508999824523926, 0.16098999977111816, 0.12756000459194183, -0.453220009803772, 0.18074999749660492, 2.941999912261963, -0.3591099977493286, -1.635200023651123, -0.5489500164985657, 0.3075999915599823, -0.30856001377105713, 0.6294900178909302, 0.2975899875164032, -1.1200000047683716, -0.22436000406742096, 0.17969000339508057, -0.7177900075912476, -0.2755599915981293, 0.4368300139904022, -0.3391300141811371, -0.49463000893592834, 0.30445000529289246, 1.055999994277954, -0.2322400063276291, -0.3463500142097473], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [-0.25589001178741455, 0.475380003452301, 0.7541599869728088, -1.0972000360488892, -0.03757200017571449, 0.12092000246047974, -0.10886000096797943, -0.45541998744010925, 0.31373998522758484, 0.792930006980896, 0.20958000421524048, -0.4230400025844574, 0.6352499723434448, -0.004692200105637312, -0.20428000390529633, 0.49470001459121704, -0.0818910002708435, -0.3066900074481964, -0.6073399782180786, -0.6266099810600281, -0.20518000423908234, -0.2254599928855896, 0.1523600071668625, -0.20350000262260437, -0.2618499994277954, -1.312000036239624, 0.4550899863243103, 0.6586300134658813, 0.7780399918556213, 1.316100001335144, 3.791599988937378, 0.24890999495983124, 0.9424899816513062, 0.11289999634027481, 0.8307399749755859, -0.2911800146102905, -0.2822999954223633, 0.3947499990463257, 0.46751999855041504, -0.7595800161361694, -0.36768001317977905, 0.6307500004768372, 0.43536999821662903, 0.41161999106407166, 0.056963000446558, -0.3820900022983551, 0.6302599906921387, -0.1350100040435791, 0.2679100036621094, 0.2717899978160858], [0.8899999856948853, 0.002224799944087863, 1.0092999935150146, -0.5579800009727478, -0.2847599983215332, 0.3015199899673462, -0.15117999911308289, -0.768530011177063, 0.4413500130176544, 0.2273699939250946, -0.45813998579978943, -0.197720006108284, 0.10352999716997147, -0.8996099829673767, 1.0729000568389893, 0.10176999866962433, 0.1511400043964386, 0.5904099941253662, -0.35506001114845276, -0.8780199885368347, 0.7881199717521667, -0.852429986000061, -0.743369996547699, -0.711899995803833, -0.2632499933242798, -1.1461000442504883, -0.042493000626564026, -0.28891000151634216, 0.6503499746322632, 0.45462000370025635, 3.4999001026153564, 0.8102899789810181, 0.2817699909210205, 0.3609499931335449, 0.17219999432563782, 0.05007199943065643, 0.2849000096321106, 0.618340015411377, 0.3574100136756897, -0.4717400074005127, -0.04534199833869934, 0.05402600020170212, 0.676010012626648, 0.632319986820221, -0.6344000101089478, -0.09376700222492218, -0.19312000274658203, 0.7126299738883972, -0.15523000061511993, 0.6162499785423279], [1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [1.058500051498413, -0.7914100289344788, 0.5160999894142151, 0.3919900059700012, 0.43303000926971436, 0.21626999974250793, 0.09367399662733078, -0.8812199831008911, 0.3351599872112274, -0.35401999950408936, 0.7120000123977661, 0.829800009727478, -0.1900400072336197, 1.736299991607666, -0.11361999809741974, -0.1298999935388565, -0.18643000721931458, 1.7835999727249146, -0.8685500025749207, -0.3509100079536438, -0.07019399851560593, 0.15271000564098358, -0.6270099878311157, -0.008863699622452259, 0.87704998254776, -0.7285699844360352, -0.6859700083732605, -0.557919979095459, 0.08540800213813782, -0.48697999119758606, 1.3454999923706055, -0.2607100009918213, -0.7709699869155884, 0.15249000489711761, -0.26388001441955566, 1.1456999778747559, 0.07382900267839432, -0.013770000077784061, -0.29058000445365906, -0.8392199873924255, 0.04517599940299988, -0.4011400043964386, -0.09980600327253342, 0.07444199919700623, 0.7221500277519226, -0.1408900022506714, 1.0944000482559204, -0.8589100241661072, -0.11517000198364258, 0.17584000527858734], [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]]

In [22]:
#Save real graphs with node types for graph generation using Diffusion Models 
torch.save([adj_list,node_type_list],'real_dblp_15.pt')

In [23]:
#Load graphs
adjs, node_types = torch.load('real_dblp_15.pt')

In [24]:
for i, adj in enumerate(adjs[:1]):
    print('adjacency matrix', adj)
    print('node types', node_types[i])

adjacency matrix tensor([[0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0],
        [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]])
node types [0, 0, 0, 0, 2, 2, 2, 1, 0, 2, 2, 0, 2, 1, 0]